type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 60
    error: 70
  allowed_symbols: ["_"] # these are allowed in type names

disabled_rules:
    - line_length
    - vertical_parameter_alignment
    - conditional_returns_on_newline
    - opening_brace
    - trailing_whitespace
    - cyclomatic_complexity
    - function_body_length
    - file_length
    - function_parameter_count
    - type_body_length
    - large_tuple
    - identifier_name
    - first_where
    - redundant_string_enum_value
    - pattern_matching_keywords
    - notification_center_detachment
    - trailing_closure
    - multiple_closures_with_trailing_closure
    - closure_end_indentation
    - redundant_discardable_let
    - nesting
    
opt_in_rules:
    - attributes
    - closure_end_indentation
    - closure_spacing
    - conditional_returns_on_newline
    - empty_count
    - explicit_init
    - fatal_error_message
    - force_unwrapping
    - multiline_parameters
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - single_test_class
    - sorted_imports
    - switch_case_on_newline
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
excluded:
    - Carthage
    - Pods
    - Superfy/BundleFiles
    - Superfy/Superfy/BundleFiles
    - vendor
    - SuperfyUITests/SnapshotsTools/SnapshotHelper.swift
identifier_name:
    excluded:
    - id
    - to
    - in
    - at
    - of
    - up
